/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Print_Oftion_All_or_Out.java
 *
 * Created on 28 Aug, 2010, 3:39:56 PM
 */

package Dialog_class;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author mayur
 */
public class Print_Oftion_All_or_Out extends javax.swing.JDialog {

    /** Creates new form Print_Oftion_All_or_Out */
    public Print_Oftion_All_or_Out(java.awt.Frame parent, boolean modal,int l_t_k) {
        super(parent, modal);
        initComponents();
        Toolkit kit=Toolkit.getDefaultToolkit();
        Dimension d=kit.getScreenSize();
        int w=d.width;
        int h=d.height;
        this.setLocation(w-w/2-w/4,h-h/2-h/4);
        setSize(620,160);
        ALL_Lab_TestjButton1.setVisible(false);
        Out_of_Clinic_Lab_TestjButton2.setVisible(false);
        if(l_t_k!=0)
        {
            ALL_Lab_TestjButton1.setVisible(true);
            Out_of_Clinic_Lab_TestjButton2.setVisible(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ALL_jButton1 = new javax.swing.JButton();
        Only_out_of_clinic_jButton2 = new javax.swing.JButton();
        Cancle_jButton3 = new javax.swing.JButton();
        ALL_Lab_TestjButton1 = new javax.swing.JButton();
        Out_of_Clinic_Lab_TestjButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clinic_Management");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("-::- Please Select what do you want to print  -::-");

        ALL_jButton1.setText("ALL");
        ALL_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_jButton1ActionPerformed(evt);
            }
        });

        Only_out_of_clinic_jButton2.setText("Out of Clinic");
        Only_out_of_clinic_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Only_out_of_clinic_jButton2ActionPerformed(evt);
            }
        });

        Cancle_jButton3.setText("Cancle");
        Cancle_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancle_jButton3ActionPerformed(evt);
            }
        });

        ALL_Lab_TestjButton1.setText("ALL & Lab Test");
        ALL_Lab_TestjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALL_Lab_TestjButton1ActionPerformed(evt);
            }
        });

        Out_of_Clinic_Lab_TestjButton2.setText("Out of Clinic & Lab Test");
        Out_of_Clinic_Lab_TestjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Out_of_Clinic_Lab_TestjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(ALL_jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Only_out_of_clinic_jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ALL_Lab_TestjButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Out_of_Clinic_Lab_TestjButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancle_jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALL_jButton1)
                    .addComponent(Only_out_of_clinic_jButton2)
                    .addComponent(ALL_Lab_TestjButton1)
                    .addComponent(Out_of_Clinic_Lab_TestjButton2)
                    .addComponent(Cancle_jButton3))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALL_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_jButton1ActionPerformed
        // TODO add your handling code here:
        clinic_management.Diagonsis_Patient_Entry.Print_Variable="all";
        clinic_management.Diagonsis_Patient_Entry.Print_Variable_Lab_Test="no";
        dispose();
    }//GEN-LAST:event_ALL_jButton1ActionPerformed

    private void Only_out_of_clinic_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Only_out_of_clinic_jButton2ActionPerformed
        // TODO add your handling code here:
        clinic_management.Diagonsis_Patient_Entry.Print_Variable="out";
        clinic_management.Diagonsis_Patient_Entry.Print_Variable_Lab_Test="no";
        dispose();
    }//GEN-LAST:event_Only_out_of_clinic_jButton2ActionPerformed

    private void Cancle_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancle_jButton3ActionPerformed
        // TODO add your handling code here:
        clinic_management.Diagonsis_Patient_Entry.Print_Variable="cancle";
        dispose();
    }//GEN-LAST:event_Cancle_jButton3ActionPerformed

    private void ALL_Lab_TestjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALL_Lab_TestjButton1ActionPerformed
        // TODO add your handling code here:
        clinic_management.Diagonsis_Patient_Entry.Print_Variable="all";
        clinic_management.Diagonsis_Patient_Entry.Print_Variable_Lab_Test="yes";
        dispose();
    }//GEN-LAST:event_ALL_Lab_TestjButton1ActionPerformed

    private void Out_of_Clinic_Lab_TestjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Out_of_Clinic_Lab_TestjButton2ActionPerformed
        // TODO add your handling code here:
        clinic_management.Diagonsis_Patient_Entry.Print_Variable="out";
        clinic_management.Diagonsis_Patient_Entry.Print_Variable_Lab_Test="yes";
        dispose();
    }//GEN-LAST:event_Out_of_Clinic_Lab_TestjButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Print_Oftion_All_or_Out dialog = new Print_Oftion_All_or_Out(new javax.swing.JFrame(), true,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALL_Lab_TestjButton1;
    private javax.swing.JButton ALL_jButton1;
    private javax.swing.JButton Cancle_jButton3;
    private javax.swing.JButton Only_out_of_clinic_jButton2;
    private javax.swing.JButton Out_of_Clinic_Lab_TestjButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
