/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Update_D_S_M_Table.java
 *
 * Created on 8 Aug, 2010, 10:28:50 AM
 */

package Dialog_class;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;

/**
 *
 * @author mayur
 */
public class Update_D_S_M_Table extends javax.swing.JDialog {

    /** Creates new form Update_D_S_M_Table */
    int flag1;
    public Update_D_S_M_Table(java.awt.Frame parent, boolean modal,int flag) {
        super(parent, modal);
        initComponents();
        flag1=flag;
        Toolkit kit=Toolkit.getDefaultToolkit();
        Dimension d=kit.getScreenSize();
        int w=d.width;
        int h=d.height;
        this.setLocation(w-w/2-w/4,h-h/2-h/4);
        setSize(520,250);
        if(flag==1)
            Name_Lable.setText("Disease Name");
        else if(flag==2)
            Name_Lable.setText("Symptom Name");
        else if(flag==3)
            Name_Lable.setText("Medicine Name");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name_Lable = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Name_TextBox = new javax.swing.JTextField();
        Desciption_TextBox = new javax.swing.JTextField();
        Add_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update D S & M Table");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("-::- Enter the Name and Description -::-");

        Name_Lable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name_Lable.setText("Diseases Name");

        Description.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Description.setText("Description");

        Name_TextBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Desciption_TextBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Add_Button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add_Button.setText("ADD");
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name_Lable)
                            .addComponent(Description))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Desciption_TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name_TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_Button))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_Lable)
                    .addComponent(Name_TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description)
                    .addComponent(Desciption_TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(Add_Button)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed
        // TODO add your handling code here:
        String D_N=Name_TextBox.getText();
        String D_D=Desciption_TextBox.getText();
        Connection c;
        Statement st;
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            c=DriverManager.getConnection("jdbc:odbc:Clinic_Management");
            System.out.println("Connection established.");
            st=(Statement) c.createStatement();
            if(flag1==1)
            {
                st.executeUpdate("INSERT INTO Disease_Name_Details VALUES ('"+D_N+"','"+D_D+"')");
            }
            else if(flag1==2)
            {
                st.executeUpdate("INSERT INTO Symptom_Name_Details VALUES ('"+D_N+"','"+D_D+"')");
            }
            else if(flag1==3)
            {
                st.executeUpdate("INSERT INTO Medicine_Name_Details VALUES ('"+D_N+"','"+D_D+"')");
            }
            c.close();
            dispose();
        } catch (Exception e) {
            System.out.print(e);
      //  Dialog_class.Old_Patient_Dialog n=new Old_Patient_Dialog(this, true,"Error in DataBase,So try again...");
        //    n.setVisible(true);
        }
    }//GEN-LAST:event_Add_ButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Update_D_S_M_Table dialog = new Update_D_S_M_Table(new javax.swing.JFrame(), true,1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Button;
    private javax.swing.JTextField Desciption_TextBox;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Name_Lable;
    private javax.swing.JTextField Name_TextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
