/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Add_Diseases_S_M_DataBase.java
 *
 * Created on 7 Aug, 2010, 10:26:11 PM
 */

package clinic_management;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mayur
 */
public class Add_Diseases_S_M_DataBase extends javax.swing.JFrame {

    /** Creates new form Add_Diseases_S_M_DataBase */
    public Connection c;
    public Statement st;
    public  ResultSet rs1;
    public PreparedStatement pre;
    public Add_Diseases_S_M_DataBase() {
        initComponents();
        try
        {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                c=DriverManager.getConnection("jdbc:odbc:Clinic_Management");
                System.out.println("Connection established.");
                st=(Statement) c.createStatement();
        }
        catch(Exception ee1)
        {   
         Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase,So try again...");
            n.setVisible(true);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Dieases_Name = new javax.swing.JTextField();
        Diseases_Desc = new javax.swing.JTextField();
        Diseases_Add = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Symptop_Name = new javax.swing.JTextField();
        Symptop_Desc = new javax.swing.JTextField();
        Symptop_Add = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Medicine_Add = new javax.swing.JButton();
        Madicine_Name = new javax.swing.JTextField();
        Medicine_Desc = new javax.swing.JTextField();
        Finish = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Lab_Test_Name_jTextField1 = new javax.swing.JTextField();
        Normal_Range_Count_jTextField2 = new javax.swing.JTextField();
        Lab_Test_jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinic_Management");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30));
        jLabel1.setText("-::- Enter Diseases,Symptop and Medicine for Updating table -::-");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("For Diseases:-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Diseases Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Description");

        Dieases_Name.setFont(new java.awt.Font("Tahoma", 1, 14));

        Diseases_Desc.setFont(new java.awt.Font("Tahoma", 1, 14));

        Diseases_Add.setFont(new java.awt.Font("Tahoma", 1, 18));
        Diseases_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/ADD.jpg"))); // NOI18N
        Diseases_Add.setBorderPainted(false);
        Diseases_Add.setContentAreaFilled(false);
        Diseases_Add.setDefaultCapable(false);
        Diseases_Add.setFocusPainted(false);
        Diseases_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diseases_AddActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(102, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(102, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setText("For Symptom:-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("Symptom Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Description");

        Symptop_Name.setFont(new java.awt.Font("Tahoma", 1, 14));

        Symptop_Desc.setFont(new java.awt.Font("Tahoma", 1, 14));

        Symptop_Add.setFont(new java.awt.Font("Tahoma", 1, 18));
        Symptop_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/ADD.jpg"))); // NOI18N
        Symptop_Add.setBorderPainted(false);
        Symptop_Add.setContentAreaFilled(false);
        Symptop_Add.setDefaultCapable(false);
        Symptop_Add.setFocusPainted(false);
        Symptop_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Symptop_AddActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(102, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(102, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel8.setText("For Medicine:-");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel9.setText("Madicine Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Description");

        Medicine_Add.setFont(new java.awt.Font("Tahoma", 1, 18));
        Medicine_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/ADD.jpg"))); // NOI18N
        Medicine_Add.setBorderPainted(false);
        Medicine_Add.setContentAreaFilled(false);
        Medicine_Add.setDefaultCapable(false);
        Medicine_Add.setFocusPainted(false);
        Medicine_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Medicine_AddActionPerformed(evt);
            }
        });

        Madicine_Name.setFont(new java.awt.Font("Tahoma", 1, 14));

        Medicine_Desc.setFont(new java.awt.Font("Tahoma", 1, 14));

        Finish.setBackground(new java.awt.Color(0, 255, 255));
        Finish.setFont(new java.awt.Font("Tahoma", 1, 18));
        Finish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Finish.jpg"))); // NOI18N
        Finish.setBorderPainted(false);
        Finish.setContentAreaFilled(false);
        Finish.setDefaultCapable(false);
        Finish.setFocusPainted(false);
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(102, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(51, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel11.setText("For Lab Test:-");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel12.setText("Lab Test Name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel13.setText("Normal Range of Count");

        Lab_Test_Name_jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));

        Normal_Range_Count_jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14));

        Lab_Test_jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/ADD.jpg"))); // NOI18N
        Lab_Test_jButton1.setBorderPainted(false);
        Lab_Test_jButton1.setContentAreaFilled(false);
        Lab_Test_jButton1.setFocusPainted(false);
        Lab_Test_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lab_Test_jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Medicine_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Madicine_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Medicine_Add)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Diseases_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dieases_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Diseases_Add)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Symptop_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Symptop_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Symptop_Add)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(685, 685, 685))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(65, 65, 65)
                        .addComponent(Lab_Test_Name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Normal_Range_Count_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(776, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(Lab_Test_jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Finish)
                .addContainerGap(776, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Dieases_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Diseases_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Diseases_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Symptop_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Symptop_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Symptop_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(Madicine_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Medicine_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Medicine_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addComponent(Lab_Test_Name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Normal_Range_Count_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lab_Test_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Diseases_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diseases_AddActionPerformed
        // TODO add your handling code here:
        String D_N=Dieases_Name.getText();
        String D_D=Diseases_Desc.getText();
        try {
            st.executeUpdate("INSERT INTO Disease_Name_Details VALUES ('"+D_N+"','"+D_D+"')");

        } catch (SQLException e) {
            System.out.print(e);
             Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase,So try again...");
            n.setVisible(true);
        }
        Dieases_Name.setText("");
        Diseases_Desc.setText("");
    }//GEN-LAST:event_Diseases_AddActionPerformed

    private void Symptop_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Symptop_AddActionPerformed
        // TODO add your handling code here:
        String D_N=Symptop_Name.getText();
        String D_D=Symptop_Desc.getText();
        try {
            st.executeUpdate("INSERT INTO Symptom_Name_Details VALUES ('"+D_N+"','"+D_D+"')");

        } catch (SQLException e) {
            System.out.print(e);
             Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase,So try again...");
            n.setVisible(true);
        }
        Symptop_Name.setText("");
        Symptop_Desc.setText("");
    }//GEN-LAST:event_Symptop_AddActionPerformed

    private void Medicine_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Medicine_AddActionPerformed
        // TODO add your handling code here:
        String D_N=Madicine_Name.getText();
        String D_D=Medicine_Desc.getText();
        try {
            st.executeUpdate("INSERT INTO Medicine_Name_Details VALUES ('"+D_N+"','"+D_D+"')");

        } catch (SQLException e) {
            System.out.print(e);
             Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase,So try again...");
            n.setVisible(true);
        }
        Madicine_Name.setText("");
        Medicine_Desc.setText("");
    }//GEN-LAST:event_Medicine_AddActionPerformed

    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Add_Diseases_S_M_DataBase.class.getName()).log(Level.SEVERE, null, ex);
        }
            Welcome_Page n = new Welcome_Page();
            n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
            n.setVisible(true);
            dispose();
    }//GEN-LAST:event_FinishActionPerformed

    private void Lab_Test_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lab_Test_jButton1ActionPerformed
        // TODO add your handling code here:
        String L_Name=Lab_Test_Name_jTextField1.getText();
        String L_N_R=Normal_Range_Count_jTextField2.getText();
        try {
            st.executeUpdate("INSERT INTO Lab_Test_Details VALUES ('"+L_Name+"','"+L_N_R+"')");

        } catch (SQLException e) {
            System.out.print(e);
             Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase,So try again...");
            n.setVisible(true);
        }
        Lab_Test_Name_jTextField1.setText("");
        Normal_Range_Count_jTextField2.setText("");
    }//GEN-LAST:event_Lab_Test_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Diseases_S_M_DataBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dieases_Name;
    private javax.swing.JButton Diseases_Add;
    private javax.swing.JTextField Diseases_Desc;
    private javax.swing.JButton Finish;
    private javax.swing.JTextField Lab_Test_Name_jTextField1;
    private javax.swing.JButton Lab_Test_jButton1;
    private javax.swing.JTextField Madicine_Name;
    private javax.swing.JButton Medicine_Add;
    private javax.swing.JTextField Medicine_Desc;
    private javax.swing.JTextField Normal_Range_Count_jTextField2;
    private javax.swing.JButton Symptop_Add;
    private javax.swing.JTextField Symptop_Desc;
    private javax.swing.JTextField Symptop_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables

}
