/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Extra_Expence_Entry.java
 *
 * Created on 12 Aug, 2010, 10:03:06 AM
 */

package clinic_management;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mayur
 */
public class Extra_Expence_Entry extends javax.swing.JFrame {

    /** Creates new form Extra_Expence_Entry */
    public Connection c;
    public Statement st;
    public ResultSet rs1;
    int S_N=0,count=0,flag_of_item=0;
    String Item_List_String[];
    public Extra_Expence_Entry() {
        initComponents();

        try
        {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                c=DriverManager.getConnection("jdbc:odbc:Clinic_Management");
                System.out.println("Connection established.");
                st=(Statement) c.createStatement();
                 rs1 = st.executeQuery("Select Sequence_No from Extra_Expence order by Sequence_No");
                 while(rs1.next())
                 {
                     S_N=rs1.getInt("Sequence_No");
                 }
                 S_N+=1;
                 Seq_No.setText(S_N+"");
                 rs1 = st.executeQuery("Select * from Item_Name_List order by Expence_Item_Name");
                 while(rs1.next())
                 {
                     count++;
                 }
                 count++;
                 Item_List_String=new String[count];
                 count=1;
                 Item_List_String[0]=" ";
                 rs1 = st.executeQuery("Select * from Item_Name_List order by Expence_Item_Name");
                 while(rs1.next())
                 {
                     Item_List_String[count++]=rs1.getString(1);
                 }
                 Item_List.setModel(new javax.swing.DefaultComboBoxModel(Item_List_String));
        }
         catch(Exception e){
              Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
            n.setVisible(true);

         }
         java.util.Date current=new java.util.Date();
        int d=current.getDate();
        Date_Of_Payment.setSelectedIndex(d);
        int m=current.getMonth();
        Month_Of_Payment.setSelectedIndex(m+1);
        int y=current.getYear();
        //System.out.print((y+1900)+ "   ");
        Year_Of_Payment.setSelectedIndex(y-106);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Seq_No = new javax.swing.JTextField();
        Name_Of_Item = new javax.swing.JTextField();
        Name_Of_Shop = new javax.swing.JTextField();
        Name_Payment_Taker = new javax.swing.JTextField();
        Total_Cost = new javax.swing.JTextField();
        Remark = new javax.swing.JTextField();
        Date_Of_Payment = new javax.swing.JComboBox();
        Month_Of_Payment = new javax.swing.JComboBox();
        Year_Of_Payment = new javax.swing.JComboBox();
        ADD = new javax.swing.JButton();
        FINISH = new javax.swing.JButton();
        Item_List = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clinic_Management");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setText("-::- Enter your extra Expence of your Clinic-::-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("Name of Item ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setText("Name of Shop");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("Sequence Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setText("Name of Payment Taker");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("Date Payment");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setText("Total Cost");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel8.setText("Remark");

        Seq_No.setFont(new java.awt.Font("Tahoma", 1, 18));
        Seq_No.setEnabled(false);

        Name_Of_Item.setFont(new java.awt.Font("Tahoma", 1, 18));
        Name_Of_Item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Name_Of_ItemKeyTyped(evt);
            }
        });

        Name_Of_Shop.setFont(new java.awt.Font("Tahoma", 1, 18));

        Name_Payment_Taker.setFont(new java.awt.Font("Tahoma", 1, 18));

        Total_Cost.setFont(new java.awt.Font("Tahoma", 1, 18));

        Remark.setFont(new java.awt.Font("Tahoma", 1, 18));

        Date_Of_Payment.setFont(new java.awt.Font("Tahoma", 1, 18));
        Date_Of_Payment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Month_Of_Payment.setFont(new java.awt.Font("Tahoma", 1, 18));
        Month_Of_Payment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        Year_Of_Payment.setFont(new java.awt.Font("Tahoma", 1, 18));
        Year_Of_Payment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        ADD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/ADD.jpg"))); // NOI18N
        ADD.setBorderPainted(false);
        ADD.setContentAreaFilled(false);
        ADD.setDefaultCapable(false);
        ADD.setFocusPainted(false);
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        FINISH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FINISH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Finish.jpg"))); // NOI18N
        FINISH.setBorderPainted(false);
        FINISH.setContentAreaFilled(false);
        FINISH.setDefaultCapable(false);
        FINISH.setFocusPainted(false);
        FINISH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINISHActionPerformed(evt);
            }
        });

        Item_List.setFont(new java.awt.Font("Tahoma", 1, 18));
        Item_List.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Item_List.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Item_ListItemStateChanged(evt);
            }
        });

        jLabel9.setText("If not in list Write..");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Date_Of_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Month_Of_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Year_Of_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Total_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Name_Of_Shop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(Name_Payment_Taker, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(ADD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FINISH))
                                    .addComponent(Remark))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Seq_No, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(Item_List, 0, 235, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Name_Of_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)))
                                .addGap(117, 117, 117)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Seq_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Item_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Name_Of_Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Name_Of_Shop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Name_Payment_Taker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Date_Of_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month_Of_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_Of_Payment, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Total_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FINISH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
        int Seq_no=Integer.parseInt(Seq_No.getText());
        String nitem=null;
        if(flag_of_item==0)
        {
            nitem=(String) Item_List.getSelectedItem();
        }else
        {
            nitem=Name_Of_Item.getText();
            try {
                st.executeUpdate("INSERT INTO Item_Name_List VALUES ('" + nitem + "')");
            } catch (SQLException ex) {
                Logger.getLogger(Extra_Expence_Entry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        String shop=Name_Of_Shop.getText();
        String spopkerper=Name_Payment_Taker.getText();
        String scost=Total_Cost.getText();
        
        String remark=Remark.getText();
           String eDate=(String) Date_Of_Payment.getSelectedItem();
            String eMonth=(String) Month_Of_Payment.getSelectedItem();
            String eYear=(String) Year_Of_Payment.getSelectedItem();
            java.sql.Date payment_date=new java.sql.Date(Integer.parseInt(eYear)-1900,Integer.parseInt(eMonth)-1,Integer.parseInt(eDate));
            if(!scost.equals(""))
            {
                int cost=Integer.parseInt(scost);
                try{
                st.executeUpdate("INSERT INTO Extra_Expence VALUES ('"+Seq_no+"','"+nitem+"','"+shop+"','"+spopkerper+"','"+payment_date+"','"+cost+"','"+remark+"')");
                    System.out.println("nt n=st.executeUpdate(sql);");
                    
                }
                catch(SQLException ee)
                {
                    System.out.print(ee);
                        Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
                        n.setVisible(true);
                }
                S_N=S_N+1;
                Seq_No.setText(S_N+"");
                Name_Of_Item.setText("");
                Name_Of_Shop.setText("");
                Name_Payment_Taker.setText("");
                Total_Cost.setText("");
                Remark.setText("");
                Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Your Record is added, Press OK...");
                n.setVisible(true);
            }
            else
            {
                Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Please,Enter Proper Value...");
                    n.setVisible(true);
            }

    }//GEN-LAST:event_ADDActionPerformed

    private void FINISHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINISHActionPerformed
        try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Extra_Expence_Entry.class.getName()).log(Level.SEVERE, null, ex);
        }
        Welcome_Page n=new Welcome_Page();
        n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_FINISHActionPerformed

    private void Name_Of_ItemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Name_Of_ItemKeyTyped
        // TODO add your handling code here:
        flag_of_item=1;
        Item_List.setSelectedIndex(0);
    }//GEN-LAST:event_Name_Of_ItemKeyTyped

    private void Item_ListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Item_ListItemStateChanged
        // TODO add your handling code here:
        flag_of_item=0;
        Name_Of_Item.setText("");
    }//GEN-LAST:event_Item_ListItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Extra_Expence_Entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JComboBox Date_Of_Payment;
    private javax.swing.JButton FINISH;
    private javax.swing.JComboBox Item_List;
    private javax.swing.JComboBox Month_Of_Payment;
    private javax.swing.JTextField Name_Of_Item;
    private javax.swing.JTextField Name_Of_Shop;
    private javax.swing.JTextField Name_Payment_Taker;
    private javax.swing.JTextField Remark;
    private javax.swing.JTextField Seq_No;
    private javax.swing.JTextField Total_Cost;
    private javax.swing.JComboBox Year_Of_Payment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
