/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Search_Expence_Between_to_Date.java
 *
 * Created on 14 Aug, 2010, 10:31:12 AM
 */

package clinic_management;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mayur
 */
public class Income_Per_Month extends javax.swing.JFrame {

    /** Creates new form Search_Expence_Between_to_Date */
    public Connection c;
    public Statement st;
    public ResultSet rs1,rs2;
     PreparedStatement pre,pre1;
    int count=0;
    String Item_List_String[],header[],previos_temp;
    Object alldata[][];
    int month_of_day[]={31,28,31,30,31,30,31,31,30,30,30,31};
    public Income_Per_Month() {
        initComponents();
        header=new String [] {"Number","Date ","Number of Patient","Income","Expence","Profit"};
        java.util.Date current=new java.util.Date();           
        int m=current.getMonth();
        Month_Start.setSelectedIndex(m+1);
        int y=current.getYear();
        Year_Start.setSelectedIndex(y-106);
        previos_temp="abc";
        try
        {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                c=DriverManager.getConnection("jdbc:odbc:Clinic_Management");
                System.out.println("Connection established.");
                st=(Statement) c.createStatement();
                
        }
        catch(Exception e){
                Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
                n.setVisible(true);

         }
        alldata=new Object[1][6];
        Expence_table.setModel(new javax.swing.table.DefaultTableModel(alldata,header));
          
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Month_Start = new javax.swing.JComboBox();
        Year_Start = new javax.swing.JComboBox();
        Find = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Expence_table = new javax.swing.JTable();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clinic_Management");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setText("-::- Select Month  -::- ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("Month");

        Month_Start.setFont(new java.awt.Font("Tahoma", 1, 18));
        Month_Start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        Month_Start.setSelectedIndex(8);

        Year_Start.setFont(new java.awt.Font("Tahoma", 1, 18));
        Year_Start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        Year_Start.setSelectedIndex(4);

        Find.setBackground(new java.awt.Color(51, 255, 255));
        Find.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Find.jpg"))); // NOI18N
        Find.setBorderPainted(false);
        Find.setContentAreaFilled(false);
        Find.setFocusPainted(false);
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setText("Your search result are following....");

        jSeparator1.setBackground(new java.awt.Color(51, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 255, 255));

        Expence_table.setBackground(new java.awt.Color(255, 255, 204));
        Expence_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        Expence_table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Expence_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Expence_table.setIntercellSpacing(new java.awt.Dimension(3, 3));
        Expence_table.setRowHeight(22);
        jScrollPane1.setViewportView(Expence_table);

        OK.setBackground(new java.awt.Color(51, 255, 255));
        OK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/OK.jpg"))); // NOI18N
        OK.setBorderPainted(false);
        OK.setContentAreaFilled(false);
        OK.setDefaultCapable(false);
        OK.setFocusPainted(false);
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(860, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(547, 547, 547)
                .addComponent(OK)
                .addContainerGap(537, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Month_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Year_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(768, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(Find)
                .addContainerGap(967, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Month_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Year_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OK))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(Find, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Search_Expence_Between_to_Date.class.getName()).log(Level.SEVERE, null, ex);
        }
        Welcome_Page n = new Welcome_Page();
        n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        // TODO add your handling code here:
        int total_income=0;
        int total_expence=0;
        int final_expence=0;
        int final_income=0;
        alldata=null;
        int total_patient=0;
        int sd=1;
        int sm=Integer.parseInt((String)Month_Start.getSelectedItem());
        int sy=Integer.parseInt((String)Year_Start.getSelectedItem());
        String temp=sm+" "+sy;
        if(!temp.equals(previos_temp))
        {
            previos_temp=temp;
            try{
                if(((sy%4==0)&&(sy%100!=0))||(sy%400==0))
                {
                    month_of_day[1]=29;
                }
                else
                {
                    month_of_day[1]=28;
                }
                alldata=new Object[month_of_day[sm-1]+2][6];
                for(int i=0;i<month_of_day[sm-1]+2;i++)
                   for(int j=0;j<6;j++)
                       alldata[i][j]=null;

                for(int i=0;i<month_of_day[sm-1];i++)
                {
                    count=0;
                    total_income=0;
                    total_expence=0;
                    pre = c.prepareStatement("Select * from Diagosis_Details_All_Patient where Date_Of_Entry=? order by Date_Of_Entry");
                    pre.setDate(1, new java.sql.Date(sy-1900,sm-1,i+1));
                    rs1=pre.executeQuery();
                    while(rs1.next())
                       {
                           count++;
                           total_income+=rs1.getInt(6);
                       }
                    final_income+=total_income;
                    total_patient+=count;
                    pre1 = c.prepareStatement("Select * from Extra_Expence where Date_Payment=? order by Date_Payment");
                    pre1.setDate(1, new java.sql.Date(sy-1900,sm-1,i+1));
                    rs2=pre1.executeQuery();
                    while(rs2.next())
                    {
                      total_expence+=rs2.getInt(6);
                    }
                    final_expence+=total_expence;

                    alldata[i][0]=""+(i+1);
                    alldata[i][1]=(i+1)+"-"+sm+"-"+sy;
                    alldata[i][2]=""+count;
                    alldata[i][3]=""+total_income;
                    alldata[i][4]=""+total_expence;
                    alldata[i][5]=""+(total_income-total_expence);
                }
                count=month_of_day[sm-1]-1;
                alldata[count+2][1]="total";
                alldata[count+2][2]=""+total_patient;
                alldata[count+2][3]=""+final_income;
                alldata[count+2][4]=""+final_expence;
                alldata[count+2][5]=""+(final_income-final_expence);

                Expence_table.setModel(new javax.swing.table.DefaultTableModel(alldata,header));
            }
            catch(NumberFormatException ee)
            {
                Expence_table.setModel(new javax.swing.table.DefaultTableModel(new Object [][] { {null, null, null, null,null,null} },header));
                Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Please,Select your date....");
                n.setVisible(true);
            }
            catch(ArithmeticException ee)
            {
                Expence_table.setModel(new javax.swing.table.DefaultTableModel(new Object [][] { {null, null, null, null,null,null} },header));
                Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Please,Select your date proper way....");
                n.setVisible(true);
            }
            catch(NullPointerException ee)
            {
                Expence_table.setModel(new javax.swing.table.DefaultTableModel(new Object [][] { {null, null, null, null,null,null} },header));
                Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Sorry,there are no any record....");
                n.setVisible(true);
            }
            catch(Exception e)
            {
                Expence_table.setModel(new javax.swing.table.DefaultTableModel(new Object [][] { {null, null, null, null,null,null} },header));
                System.out.print(e);
               Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
                n.setVisible(true);
            }
        }
    }//GEN-LAST:event_FindActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Income_Per_Month().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Expence_table;
    private javax.swing.JButton Find;
    private javax.swing.JComboBox Month_Start;
    private javax.swing.JButton OK;
    private javax.swing.JComboBox Year_Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
