/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * New_Patient_Entry.java
 *
 * Created on 24 Jul, 2010, 4:03:41 PM
 */

package clinic_management;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mayur
 */
public class New_Patient_Entry extends javax.swing.JFrame {

    public Connection c;
    public Statement st;
    public ResultSet rs1;
    public ResultSet rs2;
    String case_no_last;
    String suggetion_list[];

    
    /** Creates new form New_Patient_Entry */
    public New_Patient_Entry() throws ClassNotFoundException {
        initComponents();
        try
        {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                c=DriverManager.getConnection("jdbc:odbc:Clinic_Management");
                System.out.println("Connection established.");
                st=(Statement) c.createStatement();
                System.out.println("Statement st=c.createStatement()");
                
                rs1 = st.executeQuery("Select Case_No from New_Patient_Details order by Case_No");
                System.out.println("nt n=st.executeUpdate(sql);");

                while(rs1.next())
                {
                    //System.out.print(rs1.getString(2));
                   case_no_last=rs1.getString("Case_No");
                }
               // System.out.print(case_no_last+"System.+1900)");
                int i=0,icase_no_last=(Integer.parseInt(case_no_last)+1);
                Case_No.setText(icase_no_last+"");
                suggetion_list=new String[icase_no_last-1];
                rs1 = st.executeQuery("Select * from New_Patient_Details order by Patient_Name");
                while(rs1.next())
                {
                    suggetion_list[i++]=rs1.getString(2);
                   //case_no_last=rs1.getString("Case_No");
                }
               // for (int j = 0; j < suggetion_list.length; j++) {
              //System.out.println( suggetion_list[j]);}
        }
        catch(SQLException e)
        {
            System.out.print("error ");
            Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
            n.setVisible(true);
        }
        java.util.Date current=new java.util.Date();
        int d=current.getDate();
        Date_of_entry.setSelectedIndex(d);
        int m=current.getMonth();
        Month_of_entry.setSelectedIndex(m+1);
        int y=current.getYear();
        //System.out.print((y+1900)+ "   ");
        Year_of_entry.setSelectedIndex(y-106);

        Update.setVisible(false);
        OK.setVisible(false);
       // Suggetion_jList.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Case_No = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Weight = new javax.swing.JTextField();
        BP_Law = new javax.swing.JTextField();
        Pulse = new javax.swing.JTextField();
        Mobile_No = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Blood_Group = new javax.swing.JComboBox();
        Date_of_entry = new javax.swing.JComboBox();
        Month_of_entry = new javax.swing.JComboBox();
        Year_of_entry = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Suggetion_jList = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();
        Height = new javax.swing.JComboBox();
        Submit = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        BP_High = new javax.swing.JTextField();
        Gender = new javax.swing.JComboBox();
        Cancle = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinic_Management");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Case Number");

        Case_No.setFont(new java.awt.Font("Tahoma", 1, 18));
        Case_No.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("Patient Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel4.setText("-::- ENTER THE ALL DETAILS FOR NEW PATIENT -::-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setText("Age");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel8.setText("Weight");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel9.setText("Blood Pressure");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel10.setText("Pulse");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel11.setText("Mobile Number");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel12.setText("Date of Entry");

        Name.setFont(new java.awt.Font("Tahoma", 1, 18));
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });

        Address.setFont(new java.awt.Font("Tahoma", 1, 18));

        Age.setFont(new java.awt.Font("Tahoma", 1, 18));

        Weight.setFont(new java.awt.Font("Tahoma", 1, 18));

        BP_Law.setFont(new java.awt.Font("Tahoma", 1, 18));

        Pulse.setFont(new java.awt.Font("Tahoma", 1, 18));

        Mobile_No.setFont(new java.awt.Font("Tahoma", 1, 18));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel13.setText("Blood Group");

        Blood_Group.setFont(new java.awt.Font("Tahoma", 1, 18));
        Blood_Group.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));

        Date_of_entry.setFont(new java.awt.Font("Tahoma", 1, 18));
        Date_of_entry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Month_of_entry.setFont(new java.awt.Font("Tahoma", 1, 18));
        Month_of_entry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        Year_of_entry.setFont(new java.awt.Font("Tahoma", 1, 18));
        Year_of_entry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        jLabel14.setText("First Name  -  Middle Name - Last Name");

        jLabel15.setText("Suggetion for Name");

        Suggetion_jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Suggetion_jListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Suggetion_jList);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel16.setText("Height");

        Height.setFont(new java.awt.Font("Tahoma", 1, 18));
        Height.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 ft 1 in", "1 ft 2 in", "1 ft 3 in", "1 ft 4 in", "1 ft 5 in", "1 ft 6 in", "1 ft 7 in", "1 ft 8 in", "1 ft 9 in", "1 ft 10 in", "1 ft 11 in", "2 ft 0 in", "2 ft 1 in", "2 ft 2 in", "2 ft 3 in", "2 ft 4 in", "2 ft 5 in", "2 ft 6 in", "2 ft 7 in", "2 ft 8 in", "2 ft 9 in", "2 ft 10 in", "2 ft 11 in", "3 ft 0 in", "3 ft 1 in", "3 ft 2 in", "3 ft 3 in", "3 ft 4 in", "3 ft 5 in", "3 ft 6 in", "3 ft 7 in", "3 ft 8 in", "3 ft 9 in", "3 ft 10 in", "3 ft 11 in", "4 ft 0 in", "4 ft 1 in", "4 ft 2 in", "4 ft 3 in", "4 ft 4 in", "4 ft 5 in", "4 ft 6 in", "4 ft 7 in", "4 ft 8 in", "4 ft 9 in", "4 ft 10 in", "4 ft 11 in", "5 ft 0 in", "5 ft 1 in", "5 ft 2 in", "5 ft 3 in", "5 ft 4 in", "5 ft 5 in", "5 ft 6 in", "5 ft 7 in", "5 ft 8 in", "5 ft 9 in", "5 ft 10 in", "5 ft 11 in", "6 ft 0 in", "6 ft 1 in", "6 ft 2 in", "6 ft 3 in", "6 ft 4 in", "6 ft 5 in" }));
        Height.setSelectedIndex(55);

        Submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Submit.jpg"))); // NOI18N
        Submit.setBorderPainted(false);
        Submit.setContentAreaFilled(false);
        Submit.setDefaultCapable(false);
        Submit.setFocusPainted(false);
        Submit.setFocusable(false);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel17.setText("Low");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel18.setText("High");

        BP_High.setFont(new java.awt.Font("Tahoma", 1, 18));

        Gender.setFont(new java.awt.Font("Tahoma", 1, 18));
        Gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        Cancle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Cancle.jpg"))); // NOI18N
        Cancle.setBorderPainted(false);
        Cancle.setContentAreaFilled(false);
        Cancle.setFocusPainted(false);
        Cancle.setFocusable(false);
        Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel19.setText("Kg");

        Update.setFont(new java.awt.Font("Tahoma", 1, 18));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        OK.setFont(new java.awt.Font("Tahoma", 1, 18));
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel20.setText("Year");

        Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Reset.jpg"))); // NOI18N
        Reset.setBorderPainted(false);
        Reset.setContentAreaFilled(false);
        Reset.setDefaultCapable(false);
        Reset.setFocusPainted(false);
        Reset.setFocusable(false);
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Case_No, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(Address)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Mobile_No, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Date_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Month_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Year_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Submit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cancle)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OK)
                                .addGap(67, 67, 67)
                                .addComponent(Update))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Weight, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Height, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                    .addComponent(Age, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Blood_Group, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pulse, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BP_Law, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BP_High, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Case_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(BP_Law, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(BP_High, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Pulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Blood_Group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Mobile_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Date_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Month_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Year_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Submit)
                        .addComponent(Update)
                        .addComponent(OK))
                    .addComponent(Cancle)
                    .addComponent(Reset))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
            int sCase_No=Integer.parseInt(Case_No.getText());
            String sName=Name.getText();
            String sAddress=Address.getText();
            String sgender=(String) Gender.getSelectedItem();
            String sAge=Age.getText();
            String sheight=(String) Height.getSelectedItem();
            String sWeight=Weight.getText();
            String sbp=BP_Law.getText()+"-"+BP_High.getText();
            String sPulse=Pulse.getText();
            String sblood_group=(String) Blood_Group.getSelectedItem();
            String sMobile_No=Mobile_No.getText();

            String eDate=(String) Date_of_entry.getSelectedItem();
            String eMonth=(String) Month_of_entry.getSelectedItem();
            String eYear=(String) Year_of_entry.getSelectedItem();
            java.sql.Date entry_date=new java.sql.Date(Integer.parseInt(eYear)-1900,Integer.parseInt(eMonth)-1,Integer.parseInt(eDate));
            
          
            
            System.out.print(sCase_No+sName+sheight+"    "+sblood_group);
            try
            {
                if(!sName.equals(""))
                {
                    st.executeUpdate("INSERT INTO New_Patient_Details VALUES ('"+sCase_No+"','"+sName+"','"+sAddress+"','"+sgender+"','"+sAge+"','"+sheight+"','"+sWeight+"','"+sbp+"','"+sPulse+"','"+sblood_group+"','"+sMobile_No+"','"+entry_date+"')");
                    System.out.println("nt n=st.executeUpdate(sql);");
                    c.close();
                    Diagonsis_Patient_Entry n=new Diagonsis_Patient_Entry(sCase_No+"", sName);
                    n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
                    n.setVisible(true);
                    dispose();
                }
                else
                {
                    Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Please,Enter Patient Name...");
                    n.setVisible(true);
                }
            }
            catch(SQLException eqe)
            {
                System.out.print("error i database");
                Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
                n.setVisible(true);
            }


    }//GEN-LAST:event_SubmitActionPerformed

    private void CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleActionPerformed
        // TODO add your handling code here:
        Welcome_Page n=new Welcome_Page();
        n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
        n.setVisible(true);
        dispose();
        try {
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(New_Patient_Entry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancleActionPerformed

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
        // TODO add your handling code here:
       // Address.setText(Name.getText());

        
    }//GEN-LAST:event_NameKeyTyped

    private void NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyReleased
        // TODO add your handling code here:
       // Address.setText(Name.getText());
       String start_with=Name.getText();
       final String[] list;
       int j=0;
        for (int i = 0; i < suggetion_list.length; i++) {
            if(suggetion_list[i].startsWith(start_with))
            {
                j++;
               // list[j]=suggetion_list[i];
            }
             //System.out.println();
        }
        list=new String[j];
        j=0;
        for (int i = 0; i < suggetion_list.length; i++) {
            if(suggetion_list[i].startsWith(start_with))
            {
                list[j++]=suggetion_list[i];
            }
             //System.out.println();
        }
        Suggetion_jList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = list;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

    }//GEN-LAST:event_NameKeyReleased
    
    private void Suggetion_jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Suggetion_jListMouseClicked
        // TODO add your handling code here:
       
        String old_patient_name=(String) Suggetion_jList.getSelectedValue();
        try {
            rs1 = st.executeQuery("Select * from New_Patient_Details where Patient_Name='"+old_patient_name+"'");
            if(rs1.next())
            {
                Case_No.setText(rs1.getString(1));
                Name.setText(rs1.getString(2));
                Address.setText(rs1.getString(3));
                Gender.setSelectedItem(rs1.getString(4));
                Age.setText(rs1.getString(5));
                Height.setSelectedItem(rs1.getString(6));
                Weight.setText(rs1.getString(7));
                String bp_String=rs1.getString(8);
                int index=bp_String.indexOf('-');
                BP_Law.setText(bp_String.substring(0, index));
                BP_High.setText(bp_String.substring(index+1, bp_String.length()));
                Pulse.setText(rs1.getString(9));
                Blood_Group.setSelectedItem(rs1.getString(10));
                Mobile_No.setText(rs1.getString(11));
                String temp_d=rs1.getString(12);

                Date_of_entry.setSelectedIndex(Integer.parseInt(temp_d.substring(8,10)));
                Month_of_entry.setSelectedIndex(Integer.parseInt(temp_d.substring(5,7)));
                //System.out.print(Integer.parseInt(temp_d.substring(0,4)));
                Year_of_entry.setSelectedIndex((Integer.parseInt(temp_d.substring(0,4))-2006));

                
            }
        } catch (SQLException ex) {
            Logger.getLogger(New_Patient_Entry.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Update.setVisible(true);
        //OK.setVisible(true);
       // Submit.setVisible(false);
    }//GEN-LAST:event_Suggetion_jListMouseClicked

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Case_No.setText((Integer.parseInt(case_no_last)+1)+"");
        Address.setText("");
        Gender.setSelectedItem("Male");
        Age.setText("");
        Height.setSelectedIndex(56);
        Weight.setText("");
        BP_Law.setText("");
        BP_High.setText("");
        Pulse.setText("");
        Blood_Group.setSelectedItem("A+");
        Mobile_No.setText("");
        java.util.Date current=new java.util.Date();
        int d=current.getDate();
        Date_of_entry.setSelectedIndex(d);
        int m=current.getMonth();
        Month_of_entry.setSelectedIndex(m+1);
        int y=current.getYear();
        //System.out.print((y+1900)+ "   ");
        Year_of_entry.setSelectedIndex(y-106);


        Submit.setVisible(true);
        Update.setVisible(false);
        OK.setVisible(false);
    }//GEN-LAST:event_ResetActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        Welcome_Page n=new Welcome_Page();
        n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
        n.setVisible(true);
        dispose();
        try {
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(New_Patient_Entry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OKActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
            String Case=Case_No.getText();
            String sName=Name.getText();
            String sAddress=Address.getText();
            String sgender=(String) Gender.getSelectedItem();
            String sAge=Age.getText();
            String sheight=(String) Height.getSelectedItem();
            String sWeight=Weight.getText();
            String sbp=BP_Law.getText()+"-"+BP_High.getText();
            String sPulse=Pulse.getText();
            String sblood_group=(String) Blood_Group.getSelectedItem();
            String sMobile_No=Mobile_No.getText();

            String eDate=(String) Date_of_entry.getSelectedItem();
            String eMonth=(String) Month_of_entry.getSelectedItem();
            String eYear=(String) Year_of_entry.getSelectedItem();
            java.sql.Date eentry_date=new java.sql.Date(Integer.parseInt(eYear)-1900,Integer.parseInt(eMonth)-1,Integer.parseInt(eDate));



            //System.out.print(sCase_No+sName+sheight+"    "+sblood_group);
            try
            {
                st.executeUpdate("UPDATE New_Patient_Details SET Address='"+sAddress+"',Gender='"+sgender+"',Age='"+sAge+"',Height='"+sheight+"',Weight='"+sWeight+"',BP='"+sbp+"',Pulse='"+sPulse+"',Blood_Group='"+sblood_group+"',Mobile_No='"+sMobile_No+"',Entry_Date='"+eentry_date+"' WHERE Patient_Name='"+sName+"'");
                System.out.println("nt n=st.executeUpdate(sql);");
                c.close();
            }
            catch(SQLException eqe)
            {
                System.out.print("error i database    ");
                eqe.printStackTrace();
            }
             Welcome_Page n=new Welcome_Page();
            n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
            n.setVisible(true);
            dispose();
    }//GEN-LAST:event_UpdateActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new New_Patient_Entry().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(New_Patient_Entry.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField BP_High;
    private javax.swing.JTextField BP_Law;
    private javax.swing.JComboBox Blood_Group;
    private javax.swing.JButton Cancle;
    private javax.swing.JTextField Case_No;
    private javax.swing.JComboBox Date_of_entry;
    private javax.swing.JComboBox Gender;
    private javax.swing.JComboBox Height;
    private javax.swing.JTextField Mobile_No;
    private javax.swing.JComboBox Month_of_entry;
    private javax.swing.JTextField Name;
    private javax.swing.JButton OK;
    private javax.swing.JTextField Pulse;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private javax.swing.JList Suggetion_jList;
    private javax.swing.JButton Update;
    private javax.swing.JTextField Weight;
    private javax.swing.JComboBox Year_of_entry;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
