/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Remove_Diseases_S_M_DataBase.java
 *
 * Created on 20 Aug, 2010, 9:23:39 PM
 */

package clinic_management;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mayur
 */
public class Remove_Diseases_S_M_DataBase extends javax.swing.JFrame {

    /** Creates new form Remove_Diseases_S_M_DataBase */
    public Connection c;
    public Statement st;
    public  ResultSet rs1;
    public PreparedStatement pre;
    public Remove_Diseases_S_M_DataBase() {
        initComponents();
        try
        {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                c=DriverManager.getConnection("jdbc:odbc:Clinic_Management");
                System.out.println("Connection established.");
                st=(Statement) c.createStatement();
                Update_list();
        }
        catch(Exception ee1)
        {
         Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase,So try again...");
            n.setVisible(true);
        }

    }
 final void Update_list()
    {
         try
         {
                rs1 = st.executeQuery("Select Disease_Name from Disease_Name_Details order by Disease_Name");
                System.out.println("nt n=st.executeUpdate(sql);");
                int count=0;
                while(rs1.next())
                {
                    count++;
                }
                final String Disease_Name_list[]=new String[count+1];
                rs1 = st.executeQuery("Select Disease_Name from Disease_Name_Details order by Disease_Name");
                System.out.println("nt n=st.executeUpdate(sql);");
                count=0;
                Disease_Name_list[count++]=" ";
                while(rs1.next())
                {
                    Disease_Name_list[count++]=rs1.getString("Disease_Name");
                }
                Disease_List.setModel(new javax.swing.DefaultComboBoxModel(Disease_Name_list));
                rs1 = st.executeQuery("Select Symptom_Name from Symptom_Name_Details order by Symptom_Name");
                System.out.println("nt n=st.executeUpdate(sql);");
                count=0;
                while(rs1.next())
                {
                    count++;
                }
                final String Symptom_Name_list[]=new String[count+1];
                rs1 = st.executeQuery("Select Symptom_Name from Symptom_Name_Details order by Symptom_Name");
                System.out.println("nt n=st.executeUpdate(sql);");
                count=0;
                Symptom_Name_list[count++]=" ";
                while(rs1.next())
                {
                    Symptom_Name_list[count++]=rs1.getString("Symptom_Name");
                }
                Symptom_List.setModel(new javax.swing.DefaultComboBoxModel(Symptom_Name_list));
                rs1 = st.executeQuery("Select Medicine_Name from Medicine_Name_Details order by Medicine_Name");
                count=0;
                while(rs1.next())
                {
                    count++;
                }
                final String Medicine_Name_list[]=new String[count+1];
                rs1 = st.executeQuery("Select Medicine_Name from Medicine_Name_Details order by Medicine_Name");
                System.out.println("nt n=st.executeUpdate(sql);");
                count=0;
                Medicine_Name_list[count++]=" ";
                while(rs1.next())
                {
                    Medicine_Name_list[count++]=rs1.getString("Medicine_Name");
                }
                Medicine_List.setModel(new javax.swing.DefaultComboBoxModel(Medicine_Name_list));

                rs1 = st.executeQuery("Select Lab_Test_Name from Lab_Test_Details order by Lab_Test_Name");
                count=0;
                while(rs1.next())
                {
                    count++;
                }
                final String Lab_Test_Name_list[]=new String[count+1];
                rs1 = st.executeQuery("Select Lab_Test_Name from Lab_Test_Details order by Lab_Test_Name");
                System.out.println("nt n=st.executeUpdate(sql);");
                count=0;
                Lab_Test_Name_list[count++]=" ";
                while(rs1.next())
                {
                    Lab_Test_Name_list[count++]=rs1.getString("Lab_Test_Name");
                }
                Lab_Test_Name_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(Lab_Test_Name_list));
        }
         catch(SQLException e)
         {

         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Disease_List = new javax.swing.JComboBox();
        Delete_Desease_jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Symptom_List = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Delete_Symptom_jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Medicine_List = new javax.swing.JComboBox();
        Delete_Medicine_jButton3 = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Lab_Test_Name_jComboBox1 = new javax.swing.JComboBox();
        Lab_Test_Delete_jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clinic_Management");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setText("-::- Select Diseases,Symptop and Medicine for Remove from List -::-");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("For Diseases:-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("Disease Name");

        Disease_List.setFont(new java.awt.Font("Tahoma", 1, 14));
        Disease_List.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Delete_Desease_jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Delete.jpg"))); // NOI18N
        Delete_Desease_jButton1.setBorderPainted(false);
        Delete_Desease_jButton1.setContentAreaFilled(false);
        Delete_Desease_jButton1.setDefaultCapable(false);
        Delete_Desease_jButton1.setFocusPainted(false);
        Delete_Desease_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Desease_jButton1ActionPerformed(evt);
            }
        });

        Symptom_List.setFont(new java.awt.Font("Tahoma", 1, 14));
        Symptom_List.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setText("For Symptom:-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setText("Symptom Name");

        Delete_Symptom_jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Delete.jpg"))); // NOI18N
        Delete_Symptom_jButton2.setBorderPainted(false);
        Delete_Symptom_jButton2.setContentAreaFilled(false);
        Delete_Symptom_jButton2.setDefaultCapable(false);
        Delete_Symptom_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Symptom_jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("For Medicine:-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setText("Medicine Name");

        Medicine_List.setFont(new java.awt.Font("Tahoma", 1, 14));
        Medicine_List.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Delete_Medicine_jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Delete.jpg"))); // NOI18N
        Delete_Medicine_jButton3.setBorderPainted(false);
        Delete_Medicine_jButton3.setContentAreaFilled(false);
        Delete_Medicine_jButton3.setDefaultCapable(false);
        Delete_Medicine_jButton3.setFocusPainted(false);
        Delete_Medicine_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Medicine_jButton3ActionPerformed(evt);
            }
        });

        finish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Finish.jpg"))); // NOI18N
        finish.setBorderPainted(false);
        finish.setContentAreaFilled(false);
        finish.setDefaultCapable(false);
        finish.setFocusPainted(false);
        finish.setFocusable(false);
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel8.setText("For Lab Test:-");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel9.setText("Lab Test Name");

        Lab_Test_Name_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Lab_Test_Delete_jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Delete.jpg"))); // NOI18N
        Lab_Test_Delete_jButton1.setBorderPainted(false);
        Lab_Test_Delete_jButton1.setContentAreaFilled(false);
        Lab_Test_Delete_jButton1.setDefaultCapable(false);
        Lab_Test_Delete_jButton1.setFocusPainted(false);
        Lab_Test_Delete_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lab_Test_Delete_jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Delete_Desease_jButton1)
                                    .addComponent(Disease_List, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete_Symptom_jButton2)
                            .addComponent(Symptom_List, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(810, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete_Medicine_jButton3)
                            .addComponent(Medicine_List, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(797, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
                    .addComponent(Lab_Test_Name_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(Lab_Test_Delete_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Disease_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete_Desease_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Symptom_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delete_Symptom_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Medicine_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete_Medicine_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Lab_Test_Name_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lab_Test_Delete_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {

        }
            Welcome_Page n = new Welcome_Page();
            n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
            n.setVisible(true);
            dispose();

    }//GEN-LAST:event_finishActionPerformed

    private void Delete_Desease_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Desease_jButton1ActionPerformed
        try {
            ResultSet executeQuery = st.executeQuery("delete from Disease_Name_Details where Disease_Name='" + Disease_List.getSelectedItem() + "'");

            } catch (SQLException ex) {
                Logger.getLogger(Remove_Diseases_S_M_DataBase.class.getName()).log(Level.SEVERE, null, ex);
            }
        Update_list();
    }//GEN-LAST:event_Delete_Desease_jButton1ActionPerformed

    private void Delete_Symptom_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Symptom_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            st.executeQuery("delete from Symptom_Name_Details where Symptom_Name='" + Symptom_List.getSelectedItem() + "'");

            } catch (SQLException ex) {
                Logger.getLogger(Remove_Diseases_S_M_DataBase.class.getName()).log(Level.SEVERE, null, ex);
            }
        Update_list();
    }//GEN-LAST:event_Delete_Symptom_jButton2ActionPerformed

    private void Delete_Medicine_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Medicine_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet executeQuery = st.executeQuery("delete from Medicine_Name_Details where Medicine_Name='" + Medicine_List.getSelectedItem() + "'");

            } catch (SQLException ex) {
                Logger.getLogger(Remove_Diseases_S_M_DataBase.class.getName()).log(Level.SEVERE, null, ex);
            }
        Update_list();
    }//GEN-LAST:event_Delete_Medicine_jButton3ActionPerformed

    private void Lab_Test_Delete_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lab_Test_Delete_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet executeQuery = st.executeQuery("delete from Lab_Test_Details where Lab_Test_Name='" + Lab_Test_Name_jComboBox1.getSelectedItem() + "'");

            } catch (SQLException ex) {
                Logger.getLogger(Remove_Diseases_S_M_DataBase.class.getName()).log(Level.SEVERE, null, ex);
            }
        Update_list();
    }//GEN-LAST:event_Lab_Test_Delete_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Remove_Diseases_S_M_DataBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_Desease_jButton1;
    private javax.swing.JButton Delete_Medicine_jButton3;
    private javax.swing.JButton Delete_Symptom_jButton2;
    private javax.swing.JComboBox Disease_List;
    private javax.swing.JButton Lab_Test_Delete_jButton1;
    private javax.swing.JComboBox Lab_Test_Name_jComboBox1;
    private javax.swing.JComboBox Medicine_List;
    private javax.swing.JComboBox Symptom_List;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

}
