/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * New_Patient_Entry.java
 *
 * Created on 24 Jul, 2010, 4:03:41 PM
 */

package clinic_management;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mayur
 */
public class Search_Petient extends javax.swing.JFrame {

    public Connection c;
    public Statement st;
    public ResultSet rs1;
    public ResultSet rs2;
    PreparedStatement pre;
    String case_no_last;
    String suggetion_list[];

    
    /** Creates new form New_Patient_Entry */
    public Search_Petient() throws ClassNotFoundException {
        initComponents();
        try
        {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                c=DriverManager.getConnection("jdbc:odbc:Clinic_Management");
                System.out.println("Connection established.");
                st=(Statement) c.createStatement();
                System.out.println("Statement st=c.createStatement()");
                
                rs1 = st.executeQuery("Select Case_No from New_Patient_Details order by Case_No");
                System.out.println("nt n=st.executeUpdate(sql);");

                while(rs1.next())
                {
                    //System.out.print(rs1.getString(2));
                   case_no_last=rs1.getString("Case_No");
                }
               // System.out.print(case_no_last+"System.+1900)");
                int i=0,icase_no_last=(Integer.parseInt(case_no_last)+1);
               // Case_No.setText(icase_no_last+"");
                suggetion_list=new String[icase_no_last-1];
                rs1 = st.executeQuery("Select * from New_Patient_Details order by Patient_Name");
                while(rs1.next())
                {
                    suggetion_list[i++]=rs1.getString(2);
                   //case_no_last=rs1.getString("Case_No");
                }
               // for (int j = 0; j < suggetion_list.length; j++) {
              //System.out.println( suggetion_list[j]);}
        }
        catch(SQLException e)
        {
            System.out.print("error ");
        }
        java.util.Date current=new java.util.Date();
        int d=current.getDate();
        Date_of_entry.setSelectedIndex(d);
        int m=current.getMonth();
        Month_of_entry.setSelectedIndex(m+1);
        int y=current.getYear();
        //System.out.print((y+1900)+ "   ");
        Year_of_entry.setSelectedIndex(y-106);

       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Case_No = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Weight = new javax.swing.JTextField();
        BP_Law = new javax.swing.JTextField();
        Pulse = new javax.swing.JTextField();
        Mobile_No = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Blood_Group = new javax.swing.JComboBox();
        Date_of_entry = new javax.swing.JComboBox();
        Month_of_entry = new javax.swing.JComboBox();
        Year_of_entry = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Suggetion_jList = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();
        Height = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        BP_High = new javax.swing.JTextField();
        Gender = new javax.swing.JComboBox();
        Cancle = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        find_button = new javax.swing.JButton();
        History = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinic_Management");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Case Number");

        Case_No.setFont(new java.awt.Font("Tahoma", 1, 18));
        Case_No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Case_NoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("OR  Patient Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel4.setText("-::- ENTER THE CASE NO OR NAME OF PATIENT -::-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setText("Age");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel8.setText("Weight");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel9.setText("Blood Pressure");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel10.setText("Pulse");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel11.setText("Mobile Number");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel12.setText("Date of Entry");

        Name.setFont(new java.awt.Font("Tahoma", 1, 18));
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });

        Address.setFont(new java.awt.Font("Tahoma", 1, 18));

        Age.setFont(new java.awt.Font("Tahoma", 1, 18));

        Weight.setFont(new java.awt.Font("Tahoma", 1, 18));

        BP_Law.setFont(new java.awt.Font("Tahoma", 1, 18));

        Pulse.setFont(new java.awt.Font("Tahoma", 1, 18));

        Mobile_No.setFont(new java.awt.Font("Tahoma", 1, 18));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel13.setText("Blood Group");

        Blood_Group.setFont(new java.awt.Font("Tahoma", 1, 18));
        Blood_Group.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));

        Date_of_entry.setFont(new java.awt.Font("Tahoma", 1, 18));
        Date_of_entry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Month_of_entry.setFont(new java.awt.Font("Tahoma", 1, 18));
        Month_of_entry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        Year_of_entry.setFont(new java.awt.Font("Tahoma", 1, 18));
        Year_of_entry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));

        jLabel14.setText("First Name  -  Middle Name - Last Name");

        jLabel15.setText("Suggetion for Name");

        Suggetion_jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Suggetion_jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Suggetion_jListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Suggetion_jList);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel16.setText("Height");

        Height.setFont(new java.awt.Font("Tahoma", 1, 18));
        Height.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 ft 1 in", "1 ft 2 in", "1 ft 3 in", "1 ft 4 in", "1 ft 5 in", "1 ft 6 in", "1 ft 7 in", "1 ft 8 in", "1 ft 9 in", "1 ft 10 in", "1 ft 11 in", "2 ft 0 in", "2 ft 1 in", "2 ft 2 in", "2 ft 3 in", "2 ft 4 in", "2 ft 5 in", "2 ft 6 in", "2 ft 7 in", "2 ft 8 in", "2 ft 9 in", "2 ft 10 in", "2 ft 11 in", "3 ft 0 in", "3 ft 1 in", "3 ft 2 in", "3 ft 3 in", "3 ft 4 in", "3 ft 5 in", "3 ft 6 in", "3 ft 7 in", "3 ft 8 in", "3 ft 9 in", "3 ft 10 in", "3 ft 11 in", "4 ft 0 in", "4 ft 1 in", "4 ft 2 in", "4 ft 3 in", "4 ft 4 in", "4 ft 5 in", "4 ft 6 in", "4 ft 7 in", "4 ft 8 in", "4 ft 9 in", "4 ft 10 in", "4 ft 11 in", "5 ft 0 in", "5 ft 1 in", "5 ft 2 in", "5 ft 3 in", "5 ft 4 in", "5 ft 5 in", "5 ft 6 in", "5 ft 7 in", "5 ft 8 in", "5 ft 9 in", "5 ft 10 in", "5 ft 11 in", "6 ft 0 in", "6 ft 1 in", "6 ft 2 in", "6 ft 3 in", "6 ft 4 in", "6 ft 5 in" }));
        Height.setSelectedIndex(55);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel17.setText("Low");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel18.setText("High");

        BP_High.setFont(new java.awt.Font("Tahoma", 1, 18));

        Gender.setFont(new java.awt.Font("Tahoma", 1, 18));
        Gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        Cancle.setFont(new java.awt.Font("Tahoma", 1, 18));
        Cancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Cancle.jpg"))); // NOI18N
        Cancle.setBorderPainted(false);
        Cancle.setContentAreaFilled(false);
        Cancle.setDefaultCapable(false);
        Cancle.setFocusPainted(false);
        Cancle.setFocusable(false);
        Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel19.setText("Kg");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel20.setText("Year");

        jSeparator1.setBackground(new java.awt.Color(51, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel21.setText("Search result is following........");

        find_button.setFont(new java.awt.Font("Tahoma", 1, 18));
        find_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Find.jpg"))); // NOI18N
        find_button.setBorderPainted(false);
        find_button.setContentAreaFilled(false);
        find_button.setDefaultCapable(false);
        find_button.setFocusPainted(false);
        find_button.setFocusable(false);
        find_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_buttonActionPerformed(evt);
            }
        });

        History.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/History.jpg"))); // NOI18N
        History.setBorderPainted(false);
        History.setContentAreaFilled(false);
        History.setDefaultCapable(false);
        History.setFocusPainted(false);
        History.setFocusable(false);
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Blood_Group, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Pulse, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BP_Law, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BP_High, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Weight, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Age, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Gender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Height, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Address, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Mobile_No, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(Date_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Month_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Year_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(History)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Cancle))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE))
                            .addComponent(jSeparator1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(Case_No, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(309, 309, 309)
                                        .addComponent(find_button)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel21)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(Case_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(BP_Law, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(BP_High, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Pulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Blood_Group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Mobile_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Date_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Month_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Year_of_entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(155, Short.MAX_VALUE)
                        .addComponent(find_button)
                        .addGap(408, 408, 408)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(History)
                    .addComponent(Cancle))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleActionPerformed
        // TODO add your handling code here:
        Welcome_Page n=new Welcome_Page();
        n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
        n.setVisible(true);
        dispose();
        try {
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(New_Patient_Entry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancleActionPerformed

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
        // TODO add your handling code here:
       // Address.setText(Name.getText());

        
    }//GEN-LAST:event_NameKeyTyped

    private void NameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyReleased
        // TODO add your handling code here:
       // Address.setText(Name.getText());
        Case_No.setText("");
       String start_with=Name.getText();
       final String[] list;
       int j=0;
        for (int i = 0; i < suggetion_list.length; i++) {
            if(suggetion_list[i].startsWith(start_with))
            {
                j++;
               // list[j]=suggetion_list[i];
            }
             //System.out.println();
        }
        list=new String[j];
        j=0;
        for (int i = 0; i < suggetion_list.length; i++) {
            if(suggetion_list[i].startsWith(start_with))
            {
                list[j++]=suggetion_list[i];
            }
             //System.out.println();
        }
        Suggetion_jList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = list;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

    }//GEN-LAST:event_NameKeyReleased
    
    private void Suggetion_jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Suggetion_jListMouseClicked
        // TODO add your handling code here:
       
        String old_patient_name=(String) Suggetion_jList.getSelectedValue();
        try {
            rs1 = st.executeQuery("Select * from New_Patient_Details where Patient_Name='"+old_patient_name+"'");
            if(rs1.next())
            {
                Case_No.setText(rs1.getString(1));
                Name.setText(rs1.getString(2));
                Address.setText(rs1.getString(3));
                Gender.setSelectedItem(rs1.getString(4));
                Age.setText(rs1.getString(5));
                Height.setSelectedItem(rs1.getString(6));
                Weight.setText(rs1.getString(7));
                String bp_String=rs1.getString(8);
                int index=bp_String.indexOf('-');
                BP_Law.setText(bp_String.substring(0, index));
                BP_High.setText(bp_String.substring(index+1, bp_String.length()));
                Pulse.setText(rs1.getString(9));
                Blood_Group.setSelectedItem(rs1.getString(10));
                Mobile_No.setText(rs1.getString(11));
                String temp_d=rs1.getString(12);

                Date_of_entry.setSelectedIndex(Integer.parseInt(temp_d.substring(8,10)));
                Month_of_entry.setSelectedIndex(Integer.parseInt(temp_d.substring(5,7)));
                //System.out.print(Integer.parseInt(temp_d.substring(0,4)));
                Year_of_entry.setSelectedIndex((Integer.parseInt(temp_d.substring(0,4))-2006));

                
            }
        } catch (SQLException ex) {
            Logger.getLogger(New_Patient_Entry.class.getName()).log(Level.SEVERE, null, ex);
            Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
            n.setVisible(true);
        }
        
    }//GEN-LAST:event_Suggetion_jListMouseClicked

    private void find_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_buttonActionPerformed
        // TODO add your handling code here:
        String Case_text=Case_No.getText();
        String Name_text=Name.getText();
        if(Case_text.equals("")&&Name_text.equals(""))
        {
            Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Please,Enter the value for Searching....");
            n.setVisible(true);
        }
        else
        {
            try {
                if(Case_text.equals(""))
                {
                     rs1 = st.executeQuery("Select * from New_Patient_Details where Patient_Name='" + Name_text + "'");
                }
                else
                {
                   int cs=Integer.parseInt(Case_text);
                   pre=c.prepareStatement("Select * from New_Patient_Details where Case_No=?");
                   pre.setInt(1, cs);
                   rs1=pre.executeQuery();
                }
//                else
//                {
//
//                    int cs=Integer.parseInt(Case_text);
//                   pre=c.prepareStatement("Select * from New_Patient_Details where Case_No=? and Patient_Name=?");
//                   pre.setInt(1, cs);
//                   pre.setString(2, Name_text);
//                   rs1=pre.executeQuery();
//                     //rs1 = st.executeQuery("Select * from New_Patient_Details where Case_No='" + cs + "' and Patient_Name='" + Name_text + "'");
//                }
                if(rs1.next())
                {
                    Case_No.setText(rs1.getString(1));
                    Name.setText(rs1.getString(2));
                    Address.setText(rs1.getString(3));
                    Gender.setSelectedItem(rs1.getString(4));
                    Age.setText(rs1.getString(5));
                    Height.setSelectedItem(rs1.getString(6));
                    Weight.setText(rs1.getString(7));
                    String bp_String=rs1.getString(8);
                    int index=bp_String.indexOf('-');
                    BP_Law.setText(bp_String.substring(0, index));
                    BP_High.setText(bp_String.substring(index+1, bp_String.length()));
                    Pulse.setText(rs1.getString(9));
                    Blood_Group.setSelectedItem(rs1.getString(10));
                    Mobile_No.setText(rs1.getString(11));
                    String temp_d=rs1.getString(12);

                    Date_of_entry.setSelectedIndex(Integer.parseInt(temp_d.substring(8,10)));
                    Month_of_entry.setSelectedIndex(Integer.parseInt(temp_d.substring(5,7)));
                    //System.out.print(Integer.parseInt(temp_d.substring(0,4)));
                    Year_of_entry.setSelectedIndex((Integer.parseInt(temp_d.substring(0,4))-2006));
                }
                else
                {
                    Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Sorry,This patient entry doesn't exit.....");
                    n.setVisible(true);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Old_P_Entry.class.getName()).log(Level.SEVERE, null, ex);
                Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
                n.setVisible(true);
            }

        }

    }//GEN-LAST:event_find_buttonActionPerformed

    private void Case_NoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Case_NoKeyReleased
        // TODO add your handling code here:
        Name.setText("");
    }//GEN-LAST:event_Case_NoKeyReleased

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        // TODO add your handling code here:
        if(!Name.getText().equals("")&&!Case_No.getText().equals(""))
        {
            Previous_Record_Details n=new Previous_Record_Details(Case_No.getText(), Name.getText(),3);
            n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
            n.setVisible(true);
            dispose();
        }
         else
        {
               Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Please enter patient case_no Or name first...");
               n.setVisible(true);
        }
    }//GEN-LAST:event_HistoryActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Search_Petient().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(New_Patient_Entry.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField BP_High;
    private javax.swing.JTextField BP_Law;
    private javax.swing.JComboBox Blood_Group;
    private javax.swing.JButton Cancle;
    private javax.swing.JTextField Case_No;
    private javax.swing.JComboBox Date_of_entry;
    private javax.swing.JComboBox Gender;
    private javax.swing.JComboBox Height;
    private javax.swing.JButton History;
    private javax.swing.JTextField Mobile_No;
    private javax.swing.JComboBox Month_of_entry;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Pulse;
    private javax.swing.JList Suggetion_jList;
    private javax.swing.JTextField Weight;
    private javax.swing.JComboBox Year_of_entry;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton find_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
