/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Search_Expence_Between_to_Date.java
 *
 * Created on 14 Aug, 2010, 10:31:12 AM
 */

package clinic_management;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableColumn;

/**
 *
 * @author mayur
 */
public class Search_Expence_Between_to_Date extends javax.swing.JFrame {

    /** Creates new form Search_Expence_Between_to_Date */
    public Connection c;
    public Statement st;
    public ResultSet rs1;
     PreparedStatement pre;
    int count=0;
    long total=0;
    String Item_List_String[],header[];
    Object alldata[][];
    public Search_Expence_Between_to_Date() {
        initComponents();
        java.util.Date current=new java.util.Date();
        Date_Start.setSelectedIndex(1);
        Date_End.setSelectedIndex(31);
        Month_Start.setSelectedIndex(1);
        Month_End.setSelectedIndex(12);
        int y=current.getYear();
        Year_Start.setSelectedIndex(y-106);
        Year_End.setSelectedIndex(y-106);
        header=new String [] {"Sequence No", "Item Name", "Shop Name", "Person Name","Date of Payment","Cost","Remark"};
        try
        {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                c=DriverManager.getConnection("jdbc:odbc:Clinic_Management");
                System.out.println("Connection established.");
                st=(Statement) c.createStatement();
                rs1 = st.executeQuery("Select * from Item_Name_List order by Expence_Item_Name");
                 while(rs1.next())
                 {
                     count++;
                 }
                 count++;
                 Item_List_String=new String[count];
                 count=1;
                 Item_List_String[0]="ALL";
                 rs1 = st.executeQuery("Select * from Item_Name_List order by Expence_Item_Name");
                 while(rs1.next())
                 {
                     Item_List_String[count++]=rs1.getString(1);
                 }

                 Item_List.setModel(new javax.swing.DefaultComboBoxModel(Item_List_String));
                 }
         catch(Exception e){
              Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
            n.setVisible(true);

         }
        alldata=new Object[1][7];
          Expence_table.setModel(new javax.swing.table.DefaultTableModel(alldata,header));
          TableColumn tb=Expence_table.getColumn("Sequence No");
          tb.setMaxWidth(85);
          tb.setMinWidth(85);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Date_Start = new javax.swing.JComboBox();
        Month_Start = new javax.swing.JComboBox();
        Year_Start = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Date_End = new javax.swing.JComboBox();
        Month_End = new javax.swing.JComboBox();
        Year_End = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Item_List = new javax.swing.JComboBox();
        Find = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Expence_table = new javax.swing.JTable();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clinic_Management");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setText("-::- Select Range of Date and  Item -::- ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("Start Date");

        Date_Start.setFont(new java.awt.Font("Tahoma", 1, 18));
        Date_Start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Month_Start.setFont(new java.awt.Font("Tahoma", 1, 18));
        Month_Start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        Year_Start.setFont(new java.awt.Font("Tahoma", 1, 18));
        Year_Start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("End Date");

        Date_End.setFont(new java.awt.Font("Tahoma", 1, 18));
        Date_End.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Month_End.setFont(new java.awt.Font("Tahoma", 1, 18));
        Month_End.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        Year_End.setFont(new java.awt.Font("Tahoma", 1, 18));
        Year_End.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setText("Name of Item");

        Item_List.setFont(new java.awt.Font("Tahoma", 1, 18));
        Item_List.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Find.setBackground(new java.awt.Color(51, 255, 255));
        Find.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/Find.jpg"))); // NOI18N
        Find.setBorderPainted(false);
        Find.setContentAreaFilled(false);
        Find.setDefaultCapable(false);
        Find.setFocusPainted(false);
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setText("Your search result are following....");

        jSeparator1.setBackground(new java.awt.Color(51, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 255, 255));

        Expence_table.setBackground(new java.awt.Color(255, 255, 204));
        Expence_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Expence_table.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Expence_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Expence_table.setIntercellSpacing(new java.awt.Dimension(3, 3));
        Expence_table.setRowHeight(20);
        jScrollPane1.setViewportView(Expence_table);

        OK.setBackground(new java.awt.Color(51, 255, 255));
        OK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/buttons/OK.jpg"))); // NOI18N
        OK.setBorderPainted(false);
        OK.setContentAreaFilled(false);
        OK.setDefaultCapable(false);
        OK.setFocusPainted(false);
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(860, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(547, 547, 547)
                .addComponent(OK)
                .addContainerGap(537, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addComponent(Date_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Month_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Year_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Date_End, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Month_End, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Year_End, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Find)
                                    .addComponent(Item_List, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Month_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Date_End, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month_End, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_End, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(Item_List, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(Find, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OK)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Search_Expence_Between_to_Date.class.getName()).log(Level.SEVERE, null, ex);
        }
        Welcome_Page n = new Welcome_Page();
        n.setSize(clinic_management.Main.d.width,clinic_management.Main.d.height-40);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_OKActionPerformed

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        // TODO add your handling code here:
        try{
            int sd=Integer.parseInt((String)Date_Start.getSelectedItem());
            int sm=Integer.parseInt((String)Month_Start.getSelectedItem());
            int sy=Integer.parseInt((String)Year_Start.getSelectedItem());
            int ed=Integer.parseInt((String)Date_End.getSelectedItem());
            int em=Integer.parseInt((String)Month_End.getSelectedItem());
            int ey=Integer.parseInt((String)Year_End.getSelectedItem());
            java.sql.Date StartDate=new java.sql.Date(sy-1900,sm-1,sd);
           java.sql.Date EndDate=new java.sql.Date(ey-1900,em-1,ed);
           if(0<(StartDate.compareTo(EndDate)))
                {
                    throw new ArithmeticException();
                }
           String Item_Selected_String=(String) Item_List.getSelectedItem();
           if(Item_Selected_String.equals("ALL"))
           {
               pre = c.prepareStatement("Select * from Extra_Expence where Date_Payment>=? and Date_Payment<=?");
               pre.setDate(1, StartDate);
               pre.setDate(2, EndDate);
           }
           else
           {
               pre = c.prepareStatement("Select * from Extra_Expence where Date_Payment>=? and Date_Payment<=? and Name_Of_Expense=? ");
               pre.setDate(1, StartDate);
               pre.setDate(2, EndDate);
               pre.setString(3,Item_Selected_String);
           }
               
               rs1=pre.executeQuery();
               count=0;
               while(rs1.next())
               {
                    count++;
               }
               alldata=new Object[count+2][7];
               for(int i=0;i<count+2;i++)
                   for(int j=0;j<7;j++)
                       alldata[i][j]=null;
               count=0;
               total=0;
               
               rs1=pre.executeQuery();
               while(rs1.next())
               {
                    alldata[count][0]="  "+(count+1);
                     alldata[count][1]=rs1.getString(2);
                     alldata[count][2]=rs1.getString(3);
                     alldata[count][3]=rs1.getString(4);

                     java.sql.Date date_temp=rs1.getDate(5);//getString(12);
                     alldata[count][4]=date_temp.getDate()+"-"+(date_temp.getMonth()+1)+"-"+(date_temp.getYear()+1900);
                     int cost=rs1.getInt(6);
                     total+=cost;
                     alldata[count][5]=" "+cost;
                     alldata[count][6]=rs1.getString(7);
                     count++;
               }
                alldata[count+1][4]="Total";
                alldata[count+1][5]=" "+total;
                Expence_table.setModel(new javax.swing.table.DefaultTableModel(alldata,header));
                TableColumn tb=Expence_table.getColumn("Sequence No");
                tb.setMaxWidth(85);
                tb.setMinWidth(85);
           
        }
        catch(ArithmeticException ee)
        {
            Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Please,Select your date proper way....");
            n.setVisible(true);
        }
        catch(NumberFormatException ee)
        {
            Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Please,Select your date....");
            n.setVisible(true);
        }
        catch(Exception e)
        {
           Dialog_class.Old_Patient_Dialog n=new Dialog_class.Old_Patient_Dialog(this, true,"Error in DataBase..So try Again...");
            n.setVisible(true);
        }
    }//GEN-LAST:event_FindActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Expence_Between_to_Date().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Date_End;
    private javax.swing.JComboBox Date_Start;
    private javax.swing.JTable Expence_table;
    private javax.swing.JButton Find;
    private javax.swing.JComboBox Item_List;
    private javax.swing.JComboBox Month_End;
    private javax.swing.JComboBox Month_Start;
    private javax.swing.JButton OK;
    private javax.swing.JComboBox Year_End;
    private javax.swing.JComboBox Year_Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
