/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Welcome_Page.java
 *
 * Created on 20 Jul, 2010, 10:58:11 PM
 */

package clinic_management;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mayur
 */
public class Welcome_Page extends javax.swing.JFrame {
    int Width,Height;
    /** Creates new form Welcome_Page */
    public Welcome_Page() {
        initComponents();
        Width=clinic_management.Main.d.width;
        Height=clinic_management.Main.d.height-40;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Picture = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Lab_Test_Result_jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        HISTORY_jButton4 = new javax.swing.JButton();
        PER_Day_PatientsjButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        New_Patient = new javax.swing.JMenuItem();
        Old_Patient = new javax.swing.JMenuItem();
        Lab_Test_Result_jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Between_two_Date = new javax.swing.JMenuItem();
        Per_Day_Patients = new javax.swing.JMenuItem();
        As_Per_Desease_jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AllDetailsofPatient = new javax.swing.JMenuItem();
        History_Of_Perticular_Patient = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Add_Disease = new javax.swing.JMenuItem();
        Add_Symptom = new javax.swing.JMenuItem();
        Add_Medicine = new javax.swing.JMenuItem();
        ADD_LAB_Test = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Remove_Disease = new javax.swing.JMenuItem();
        Remove_Symptom = new javax.swing.JMenuItem();
        Remove_Medicine = new javax.swing.JMenuItem();
        Remove_Lab_Test = new javax.swing.JMenuItem();
        MAINTAINENCE = new javax.swing.JMenu();
        ADD_EXPENCE = new javax.swing.JMenuItem();
        VIEW_ALL_EXPENCE = new javax.swing.JMenuItem();
        SEARCH_EXPENCE = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Income_Per_Day = new javax.swing.JMenuItem();
        Income_Per_Month = new javax.swing.JMenuItem();
        Income_Per_Year = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Income_Per_Perticular_Patient = new javax.swing.JMenuItem();
        Income_Per_All_Petient = new javax.swing.JMenuItem();
        Visitors = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinic_Management");
        setBackground(new java.awt.Color(204, 255, 255));
        setFocusCycleRoot(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(247, 173, 59));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master page image/Old Patient.jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master page image/New Patient.jpg"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master page image/View All Patients.jpg"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master page image/Clinic Management.jpg"))); // NOI18N

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master page image/Exit.jpg"))); // NOI18N
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setDefaultCapable(false);
        Exit.setFocusCycleRoot(true);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Lab_Test_Result_jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master page image/Lab Test Result.jpg"))); // NOI18N
        Lab_Test_Result_jButton6.setBorderPainted(false);
        Lab_Test_Result_jButton6.setContentAreaFilled(false);
        Lab_Test_Result_jButton6.setFocusPainted(false);
        Lab_Test_Result_jButton6.setFocusable(false);
        Lab_Test_Result_jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lab_Test_Result_jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/[gickr.com]_816f0ec9-188b-23e4-f17b-c73ceee048ad.gif"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 4));

        HISTORY_jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master page image/History of Patients.jpg"))); // NOI18N
        HISTORY_jButton4.setBorderPainted(false);
        HISTORY_jButton4.setContentAreaFilled(false);
        HISTORY_jButton4.setDefaultCapable(false);
        HISTORY_jButton4.setFocusPainted(false);
        HISTORY_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HISTORY_jButton4ActionPerformed(evt);
            }
        });

        PER_Day_PatientsjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master page image/Per Day patients.jpg"))); // NOI18N
        PER_Day_PatientsjButton5.setBorderPainted(false);
        PER_Day_PatientsjButton5.setContentAreaFilled(false);
        PER_Day_PatientsjButton5.setDefaultCapable(false);
        PER_Day_PatientsjButton5.setFocusPainted(false);
        PER_Day_PatientsjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PER_Day_PatientsjButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Picture))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lab_Test_Result_jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(59, 59, 59)))
                            .addComponent(jButton2))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HISTORY_jButton4)
                            .addComponent(PER_Day_PatientsjButton5)
                            .addComponent(jButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(593, 593, 593)
                        .addComponent(Exit)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Picture)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(HISTORY_jButton4)
                                .addGap(26, 26, 26)
                                .addComponent(PER_Day_PatientsjButton5)
                                .addGap(31, 31, 31)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(Lab_Test_Result_jButton6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(Exit)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jMenu1.setBorder(null);
        jMenu1.setText("ADD PATIENT ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18));

        New_Patient.setFont(new java.awt.Font("Tahoma", 1, 18));
        New_Patient.setText("New Patient");
        New_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_PatientActionPerformed(evt);
            }
        });
        jMenu1.add(New_Patient);

        Old_Patient.setFont(new java.awt.Font("Tahoma", 1, 18));
        Old_Patient.setText("Old  Patient");
        Old_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Old_PatientActionPerformed(evt);
            }
        });
        jMenu1.add(Old_Patient);

        Lab_Test_Result_jMenuItem4.setFont(new java.awt.Font("Tahoma", 1, 18));
        Lab_Test_Result_jMenuItem4.setText("Lab Test Result");
        Lab_Test_Result_jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lab_Test_Result_jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(Lab_Test_Result_jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(null);
        jMenu2.setText("VIEW");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18));

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jMenuItem3.setText("All Patient Profile");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        Between_two_Date.setFont(new java.awt.Font("Tahoma", 1, 18));
        Between_two_Date.setText("Between two Date");
        Between_two_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Between_two_DateActionPerformed(evt);
            }
        });
        jMenu2.add(Between_two_Date);

        Per_Day_Patients.setFont(new java.awt.Font("Tahoma", 1, 18));
        Per_Day_Patients.setText("Per Day Patients");
        Per_Day_Patients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Per_Day_PatientsActionPerformed(evt);
            }
        });
        jMenu2.add(Per_Day_Patients);

        As_Per_Desease_jMenuItem4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        As_Per_Desease_jMenuItem4.setText("As Per Disease");
        As_Per_Desease_jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                As_Per_Desease_jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(As_Per_Desease_jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(null);
        jMenu3.setText("SEARCH");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18));

        AllDetailsofPatient.setFont(new java.awt.Font("Tahoma", 1, 18));
        AllDetailsofPatient.setText("All Details of Patient ");
        AllDetailsofPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllDetailsofPatientActionPerformed(evt);
            }
        });
        jMenu3.add(AllDetailsofPatient);

        History_Of_Perticular_Patient.setFont(new java.awt.Font("Tahoma", 1, 18));
        History_Of_Perticular_Patient.setText("History Of Perticular Patient");
        History_Of_Perticular_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                History_Of_Perticular_PatientActionPerformed(evt);
            }
        });
        jMenu3.add(History_Of_Perticular_Patient);

        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(null);
        jMenu4.setText("ADD/REMOVE");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18));

        Add_Disease.setFont(new java.awt.Font("Tahoma", 1, 18));
        Add_Disease.setText("Add Disease");
        Add_Disease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_DiseaseActionPerformed(evt);
            }
        });
        jMenu4.add(Add_Disease);

        Add_Symptom.setFont(new java.awt.Font("Tahoma", 1, 18));
        Add_Symptom.setText("Add Symptom");
        Add_Symptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_SymptomActionPerformed(evt);
            }
        });
        jMenu4.add(Add_Symptom);

        Add_Medicine.setFont(new java.awt.Font("Tahoma", 1, 18));
        Add_Medicine.setText("Add Medicine");
        Add_Medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_MedicineActionPerformed(evt);
            }
        });
        jMenu4.add(Add_Medicine);

        ADD_LAB_Test.setFont(new java.awt.Font("Tahoma", 1, 18));
        ADD_LAB_Test.setText("Add Lab Test");
        ADD_LAB_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_LAB_TestActionPerformed(evt);
            }
        });
        jMenu4.add(ADD_LAB_Test);
        jMenu4.add(jSeparator3);

        Remove_Disease.setFont(new java.awt.Font("Tahoma", 1, 18));
        Remove_Disease.setText("Remove Disease");
        Remove_Disease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_DiseaseActionPerformed(evt);
            }
        });
        jMenu4.add(Remove_Disease);

        Remove_Symptom.setFont(new java.awt.Font("Tahoma", 1, 18));
        Remove_Symptom.setText("Remove Symptom");
        Remove_Symptom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_SymptomActionPerformed(evt);
            }
        });
        jMenu4.add(Remove_Symptom);

        Remove_Medicine.setFont(new java.awt.Font("Tahoma", 1, 18));
        Remove_Medicine.setText("Remove Medicine");
        Remove_Medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_MedicineActionPerformed(evt);
            }
        });
        jMenu4.add(Remove_Medicine);

        Remove_Lab_Test.setFont(new java.awt.Font("Tahoma", 1, 18));
        Remove_Lab_Test.setText("Remove Lab Test");
        Remove_Lab_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_Lab_TestActionPerformed(evt);
            }
        });
        jMenu4.add(Remove_Lab_Test);

        jMenuBar1.add(jMenu4);

        MAINTAINENCE.setText("MAINTAINENCE");
        MAINTAINENCE.setFont(new java.awt.Font("Tahoma", 1, 18));

        ADD_EXPENCE.setFont(new java.awt.Font("Tahoma", 1, 18));
        ADD_EXPENCE.setText("Add Expence");
        ADD_EXPENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_EXPENCEActionPerformed(evt);
            }
        });
        MAINTAINENCE.add(ADD_EXPENCE);

        VIEW_ALL_EXPENCE.setFont(new java.awt.Font("Tahoma", 1, 18));
        VIEW_ALL_EXPENCE.setText("View All Expence");
        VIEW_ALL_EXPENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEW_ALL_EXPENCEActionPerformed(evt);
            }
        });
        MAINTAINENCE.add(VIEW_ALL_EXPENCE);

        SEARCH_EXPENCE.setFont(new java.awt.Font("Tahoma", 1, 18));
        SEARCH_EXPENCE.setText("Search Expence");
        SEARCH_EXPENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_EXPENCEActionPerformed(evt);
            }
        });
        MAINTAINENCE.add(SEARCH_EXPENCE);
        MAINTAINENCE.add(jSeparator1);

        Income_Per_Day.setFont(new java.awt.Font("Tahoma", 1, 18));
        Income_Per_Day.setText("Income Per Day ");
        Income_Per_Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Income_Per_DayActionPerformed(evt);
            }
        });
        MAINTAINENCE.add(Income_Per_Day);

        Income_Per_Month.setFont(new java.awt.Font("Tahoma", 1, 18));
        Income_Per_Month.setText("Income Per Month");
        Income_Per_Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Income_Per_MonthActionPerformed(evt);
            }
        });
        MAINTAINENCE.add(Income_Per_Month);

        Income_Per_Year.setFont(new java.awt.Font("Tahoma", 1, 18));
        Income_Per_Year.setText("Income Per Year");
        Income_Per_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Income_Per_YearActionPerformed(evt);
            }
        });
        MAINTAINENCE.add(Income_Per_Year);
        MAINTAINENCE.add(jSeparator2);

        Income_Per_Perticular_Patient.setFont(new java.awt.Font("Tahoma", 1, 18));
        Income_Per_Perticular_Patient.setText("Income Per Perticular Patient");
        Income_Per_Perticular_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Income_Per_Perticular_PatientActionPerformed(evt);
            }
        });
        MAINTAINENCE.add(Income_Per_Perticular_Patient);

        Income_Per_All_Petient.setFont(new java.awt.Font("Tahoma", 1, 18));
        Income_Per_All_Petient.setText("Income Per All Petient");
        Income_Per_All_Petient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Income_Per_All_PetientActionPerformed(evt);
            }
        });
        MAINTAINENCE.add(Income_Per_All_Petient);

        jMenuBar1.add(MAINTAINENCE);

        Visitors.setText("VISITORS");
        Visitors.setFont(new java.awt.Font("Tahoma", 1, 18));

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jMenuItem1.setText("Add Visitor");
        Visitors.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jMenuItem2.setText("View Visitor");
        Visitors.add(jMenuItem2);

        jMenuBar1.add(Visitors);

        Help.setText("HELP");
        Help.setFont(new java.awt.Font("Tahoma", 1, 18));

        about.setFont(new java.awt.Font("Tahoma", 1, 18));
        about.setText("About");
        Help.add(about);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void New_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_PatientActionPerformed
        // TODO add your handling code here:
          New_Patient_Entry n = null;
        try {
            n = new New_Patient_Entry();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_New_PatientActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        View_all_Patient_Details n=new View_all_Patient_Details();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void Old_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Old_PatientActionPerformed
        // TODO add your handling code here:
        Old_P_Entry n = null;
        try {
            n = new Old_P_Entry();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Old_PatientActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Old_P_Entry n = null;
        try {
            n = new Old_P_Entry();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        New_Patient_Entry n = null;
        try {
            n = new New_Patient_Entry();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         View_all_Patient_Details n=new View_all_Patient_Details();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ADD_EXPENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_EXPENCEActionPerformed
        // TODO add your handling code here:
        Extra_Expence_Entry n=new Extra_Expence_Entry();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_ADD_EXPENCEActionPerformed

    private void VIEW_ALL_EXPENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEW_ALL_EXPENCEActionPerformed
        // TODO add your handling code here:
        View_All_Extra_Expence n=new View_All_Extra_Expence();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_VIEW_ALL_EXPENCEActionPerformed

    private void SEARCH_EXPENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_EXPENCEActionPerformed
        // TODO add your handling code here:
        Search_Expence_Between_to_Date n=new Search_Expence_Between_to_Date();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_SEARCH_EXPENCEActionPerformed

    private void Between_two_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Between_two_DateActionPerformed
        // TODO add your handling code here:
        Search_Patient_Between_to_Date n=new Search_Patient_Between_to_Date(2);
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Between_two_DateActionPerformed

    private void Per_Day_PatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Per_Day_PatientsActionPerformed
        // TODO add your handling code here:
        Search_Patient_Between_to_Date n=new Search_Patient_Between_to_Date(1);
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Per_Day_PatientsActionPerformed

    private void History_Of_Perticular_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_History_Of_Perticular_PatientActionPerformed
        // TODO add your handling code here:
        Previous_Record_Details n=new Previous_Record_Details("","",2);
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_History_Of_Perticular_PatientActionPerformed

    private void Income_Per_DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Income_Per_DayActionPerformed
        // TODO add your handling code here:
        Income_Between_to_Date n=new Income_Between_to_Date(1);
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Income_Per_DayActionPerformed

    private void Add_DiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_DiseaseActionPerformed
        // TODO add your handling code here:
        Add_Diseases_S_M_DataBase n=new Add_Diseases_S_M_DataBase();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Add_DiseaseActionPerformed

    private void Add_SymptomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_SymptomActionPerformed
        // TODO add your handling code here:
        Add_Diseases_S_M_DataBase n=new Add_Diseases_S_M_DataBase();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Add_SymptomActionPerformed

    private void Add_MedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_MedicineActionPerformed
        // TODO add your handling code here:
        Add_Diseases_S_M_DataBase n=new Add_Diseases_S_M_DataBase();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Add_MedicineActionPerformed

    private void AllDetailsofPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllDetailsofPatientActionPerformed
        // TODO add your handling code here:
        Search_Petient n = null;
        try {
            n = new Search_Petient();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_AllDetailsofPatientActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void Income_Per_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Income_Per_MonthActionPerformed
        // TODO add your handling code here:
        Income_Per_Month n=new Income_Per_Month();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Income_Per_MonthActionPerformed

    private void Income_Per_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Income_Per_YearActionPerformed
        // TODO add your handling code here:
        Income_Per_Year n=new Income_Per_Year();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Income_Per_YearActionPerformed

    private void Income_Per_Perticular_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Income_Per_Perticular_PatientActionPerformed
        // TODO add your handling code here:
        Income_Per_Patient n=new Income_Per_Patient();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Income_Per_Perticular_PatientActionPerformed

    private void Income_Per_All_PetientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Income_Per_All_PetientActionPerformed
        // TODO add your handling code here:
        Income_Per_All_Patents n=new Income_Per_All_Patents();
       n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Income_Per_All_PetientActionPerformed

    private void Remove_DiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_DiseaseActionPerformed
        // TODO add your handling code here:
        Remove_Diseases_S_M_DataBase n=new Remove_Diseases_S_M_DataBase();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Remove_DiseaseActionPerformed

    private void Remove_SymptomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_SymptomActionPerformed
        // TODO add your handling code here:
        Remove_Diseases_S_M_DataBase n=new Remove_Diseases_S_M_DataBase();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Remove_SymptomActionPerformed

    private void Remove_MedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_MedicineActionPerformed
        // TODO add your handling code here:
        Remove_Diseases_S_M_DataBase n=new Remove_Diseases_S_M_DataBase();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Remove_MedicineActionPerformed

    private void ADD_LAB_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_LAB_TestActionPerformed
        // TODO add your handling code here:
        Add_Diseases_S_M_DataBase n=new Add_Diseases_S_M_DataBase();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_ADD_LAB_TestActionPerformed

    private void Remove_Lab_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_Lab_TestActionPerformed
        // TODO add your handling code here:
        Remove_Diseases_S_M_DataBase n=new Remove_Diseases_S_M_DataBase();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Remove_Lab_TestActionPerformed

    private void Lab_Test_Result_jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lab_Test_Result_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Lab_Test_Result_Entry n=new Lab_Test_Result_Entry();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Lab_Test_Result_jMenuItem4ActionPerformed

    private void Lab_Test_Result_jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lab_Test_Result_jButton6ActionPerformed
        // TODO add your handling code here:
        Lab_Test_Result_Entry n=new Lab_Test_Result_Entry();
       n.setSize(Width,Height);
       n.setVisible(true);
        dispose();
    }//GEN-LAST:event_Lab_Test_Result_jButton6ActionPerformed

    private void HISTORY_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HISTORY_jButton4ActionPerformed
        // TODO add your handling code here:
        Previous_Record_Details n=new Previous_Record_Details("","",2);
       n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_HISTORY_jButton4ActionPerformed

    private void PER_Day_PatientsjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PER_Day_PatientsjButton5ActionPerformed
        // TODO add your handling code here:
        Search_Patient_Between_to_Date n=new Search_Patient_Between_to_Date(1);
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_PER_Day_PatientsjButton5ActionPerformed

    private void As_Per_Desease_jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_As_Per_Desease_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        As_Per_Disease n=new As_Per_Disease();
        n.setSize(Width,Height);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_As_Per_Desease_jMenuItem4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ADD_EXPENCE;
    private javax.swing.JMenuItem ADD_LAB_Test;
    private javax.swing.JMenuItem Add_Disease;
    private javax.swing.JMenuItem Add_Medicine;
    private javax.swing.JMenuItem Add_Symptom;
    private javax.swing.JMenuItem AllDetailsofPatient;
    private javax.swing.JMenuItem As_Per_Desease_jMenuItem4;
    private javax.swing.JMenuItem Between_two_Date;
    private javax.swing.JButton Exit;
    private javax.swing.JButton HISTORY_jButton4;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem History_Of_Perticular_Patient;
    private javax.swing.JMenuItem Income_Per_All_Petient;
    private javax.swing.JMenuItem Income_Per_Day;
    private javax.swing.JMenuItem Income_Per_Month;
    private javax.swing.JMenuItem Income_Per_Perticular_Patient;
    private javax.swing.JMenuItem Income_Per_Year;
    private javax.swing.JButton Lab_Test_Result_jButton6;
    private javax.swing.JMenuItem Lab_Test_Result_jMenuItem4;
    private javax.swing.JMenu MAINTAINENCE;
    private javax.swing.JMenuItem New_Patient;
    private javax.swing.JMenuItem Old_Patient;
    private javax.swing.JButton PER_Day_PatientsjButton5;
    private javax.swing.JMenuItem Per_Day_Patients;
    private javax.swing.JLabel Picture;
    private javax.swing.JMenuItem Remove_Disease;
    private javax.swing.JMenuItem Remove_Lab_Test;
    private javax.swing.JMenuItem Remove_Medicine;
    private javax.swing.JMenuItem Remove_Symptom;
    private javax.swing.JMenuItem SEARCH_EXPENCE;
    private javax.swing.JMenuItem VIEW_ALL_EXPENCE;
    private javax.swing.JMenu Visitors;
    private javax.swing.JMenuItem about;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

}
